remote_theme: pages-themes/minimal@v0.2.0
title: TD Swinburne, CNRS
author: TD Swinburne
logo: images/face.png
lang: en-GB
show_downloads: "false"
github:
  is_project_page: "false"
  is_user_page: "false"
plugins:
- jekyll-remote-theme
- jekyll-seo-tag